spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/openschedulr}
    username: ${DB_USERNAME:openschedulr}
    password: ${DB_PASSWORD:openschedulr}
    driver-class-name: org.postgresql.Driver
